In [1]:
from tensorflow.keras.preprocessing.text import one_hot

In [2]:
### sentences
sent=[  'the glass of milk',
     'the glass of juice',
     'the cup of tea',
    'I am a good boy',
     'I am a good developer',
     'understand the meaning of words',
     'your videos are good',]

In [3]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [4]:
## Define the vocabulary size
voc_size=10000

In [5]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [6]:
### One Hot Representation
one_hot_repr=[one_hot(words,voc_size)for words in sent]
one_hot_repr

[[115, 249, 2511, 9466],
 [115, 249, 2511, 1802],
 [115, 143, 2511, 8984],
 [7795, 2725, 7903, 2119, 9614],
 [7795, 2725, 7903, 2119, 2434],
 [602, 115, 6810, 2511, 4368],
 [4856, 790, 5345, 2119]]

In [7]:
## word Embedding Representation

from tensorflow.keras.layers import Embedding
#from tensorflow.keras.processing.sequence import pad_sequences
from tensorflow.keras.utils import pad_sequences
from tensorflow.keras.models import Sequential

In [8]:
import numpy as np

In [9]:
sent_length=8
embedded_docs=pad_sequences(one_hot_repr,padding='pre',maxlen=sent_length)
print(embedded_docs)

[[   0    0    0    0  115  249 2511 9466]
 [   0    0    0    0  115  249 2511 1802]
 [   0    0    0    0  115  143 2511 8984]
 [   0    0    0 7795 2725 7903 2119 9614]
 [   0    0    0 7795 2725 7903 2119 2434]
 [   0    0    0  602  115 6810 2511 4368]
 [   0    0    0    0 4856  790 5345 2119]]


In [10]:
## feature representation
dim=10

In [11]:
# Define the Sequential model
model = Sequential()

# Add the embedding layer with input_length
model.add(Embedding(input_dim=voc_size, output_dim=dim, input_length=sent_length))

# Compile the model
model.compile(optimizer='adam', loss='mse')

/Users/anushachebolu/Documents/SimpleRNN/venv/lib/python3.12/site-packages/keras/src/layers/core/embedding.py:90: UserWarning: Argument `input_length` is deprecated. Just remove it.
  warnings.warn(


In [14]:
model.predict(embedded_docs)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 79ms/step


array([[[ 0.00989638,  0.02822617, -0.03079993, -0.02030315,
          0.00841117,  0.0256575 , -0.04099004,  0.03601389,
          0.04928306, -0.01989372],
        [ 0.00989638,  0.02822617, -0.03079993, -0.02030315,
          0.00841117,  0.0256575 , -0.04099004,  0.03601389,
          0.04928306, -0.01989372],
        [ 0.00989638,  0.02822617, -0.03079993, -0.02030315,
          0.00841117,  0.0256575 , -0.04099004,  0.03601389,
          0.04928306, -0.01989372],
        [ 0.00989638,  0.02822617, -0.03079993, -0.02030315,
          0.00841117,  0.0256575 , -0.04099004,  0.03601389,
          0.04928306, -0.01989372],
        [ 0.00231721,  0.03002447,  0.0030619 ,  0.01506373,
          0.03248278, -0.01186426, -0.04983645,  0.00876132,
          0.02954289, -0.03727224],
        [ 0.02402773, -0.0486688 , -0.02250867,  0.04886793,
         -0.00919021,  0.00070854, -0.0408702 ,  0.01590163,
          0.01321805,  0.02377245],
        [ 0.00516449,  0.01120998, -0.02621377,  0.0

In [15]:
embedded_docs[0]

array([ 0,  0,  0,  0, 41, 20, 27, 40], dtype=int32)